# Generated by Django 3.2.9 on 2023-12-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sx_surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='acciones_asesor',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='ofrecieron_cortesias',
            field=models.BooleanField(),
        ),
    ]
