# Generated by Django 3.2.9 on 2023-12-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sx_surveys', '0002_auto_20231219_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='programacion_cita',
            field=models.CharField(max_length=255),
        ),
    ]
