# Generated by Django 3.2.9 on 2024-01-11 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sx_surveys', '0005_alter_encuesta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='agencia',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='sx_surveys.agencias'),
        ),
    ]
