# Generated by Django 3.2.9 on 2024-01-30 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sx_surveys', '0008_auto_20240111_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 19, 47, 30, 530018, tzinfo=utc)),
        ),
    ]
