# Generated by Django 3.2.9 on 2024-01-30 22:56

import apps.sx_surveys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sx_surveys', '0009_alter_encuesta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='fecha',
            field=models.DateTimeField(default=apps.sx_surveys.models.default_fecha),
        ),
    ]
